### ISSUE TITLE
run release command in branches other than 'master'

### ISSUE THREAD

**Issue by shinout** [CureApp/node-circleci-autorelease#4]
``` yaml
deployment:
  create_release_branch:
    branch:
      - master
```

Customize the branch name to run `create_release_branch` deployment section.
